### ISSUE TITLE
Add local backup

### ISSUE THREAD

**Issue by tomdereub** [YunoHost-Apps/borg_ynh#80]
It would be great to be able to make local backups with borg, for instance on an external HDD.
Could it be integrated in this package ? Or is it better to create a dedicated app "borg local" ?

**Comment by zamentur** [comment]
That 's already possible
See the help message of first question during installation: https://github.com/YunoHost-Apps/borg_ynh/blob/testing/manifest.json#L32

However you have to mount hdd and set permission by yourself.

**Comment by prog-amateur2** [comment]
> However you have to mount hdd and set permission by yourself.

Hello, sorry to comment this issue a few later and after closing, but I think it is related and good for clarification : I just want to know which permission (`chmod` and `user:group`) is necessary to make borg accessing the local storage ? 

Because I have made a directory using `sudo su` (following the yunohost guide, and my path is `/media/HDD/backups`) so I am not sure borg can write in this folder. Thank you very much for your kind help.
